import Advantages from '@/components/Advantages/Advantages'
import Bussineses from '@/components/Bussineses/Bussineses'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import OurPlatfrom from '@/components/OurPlatfrom/OurPlatfrom'
import StepsToSucces from '@/components/StepsToSucces/StepsToSucces'
import VideoSliderSection from '@/components/VideoSliderSection/VideoSliderSection'
import Head from 'next/head'
import React from 'react'

export default function Franshiza() {
  return (
    <>
    <Head>
      <title>ВНК</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
        <main>
            <VideoSliderSection />
            <Bussineses />
            <Advantages />
            <OurPlatfrom />
            <StepsToSucces />
        </main>
    <Footer />
  </>
  )
}
