import FiltrMark from '@/components/FiltrMark/FiltrMark'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'


export default function gruzovik() {
    return (
        <>
        <Head>
          <title>ВНК</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <Header />
            <main className='gruzovikMain'>
                <div className={'gruzovikHeading'}>
                    <div className="routing">
                        <Link href={'/'}>Главная</Link>
                        <span>›</span>
                        <Link href={'/tehnika'}>Спец. техника</Link>
                        <span>›</span>
                        <Link href={'/gruzovik'}>Грузовики</Link>
                    </div>
                  <h2>Продажа грузового транспорта</h2>
                </div>
                <FiltrMark />
            </main>
        <Footer />
      </>
      )
    }