import Banner from "@/components/Banner/Banner";
import Category from "@/components/Category/Category";
import Header from "@/components/Header/Header";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>ВНК</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Header />
      <Category />
    </>
  );
}
