import SliderAds from '@/components/Advertisements/SliderAds'
import CategoryTwo from '@/components/Category/CategoryTwo'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import Recomendation from '@/components/Recomendation/Recomendation'
import Head from 'next/head'
import React from 'react'

export default function Tehnika() {
  return (
    <>
    <Head>
      <title>ВНК</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
        <main>
            <CategoryTwo />
            <SliderAds />
            <Recomendation />
        </main>
    <Footer />
  </>
  )
}
